#!/bin/bash

systemctl daemon-reload
systemctl enable auto-temp-ctrl.service

if ! command -v /usr/local/bin/gpio &> /dev/null; then
    echo "============================================================"
    echo "WiringOP is NOT installed!"
    echo "You must install WiringOP for auto-temp-ctrl to work properly."
    echo ""
    echo "Install now? (y/N):"
    read -r answer
    if [[ "$answer" == "y" || "$answer" == "Y" ]]; then
        git clone https://github.com/sunzone93/WiringOP-Zero.git ~/WiringOP-Zero
        cd ~/WiringOP-Zero
        chmod +x ./build
        sudo ./build
        echo ""
        echo "WiringOP installation completed."
        echo "Restarting auto-temp-ctrl service..."
        sudo systemctl restart auto-temp-ctrl.service
        exit 0
    else
        echo "You can install WiringOP later manually and restart the service:"
        echo "sudo systemctl restart auto-temp-ctrl.service"
    fi
else
    echo "WiringOP already installed."
    sudo systemctl start auto-temp-ctrl.service
fi
